Validate configured plugin options the Gatsby way
raae/gatsby-source-cloudinary pull request #5
Opened 2022-09-14 10:22 UTC by olavea

2022-09-16 13:16 UTC, raae reviewed
praise: great work, this looks correct to me

2022-09-16 13:25 UTC, raae requested changes
suggestion(blocking): add `resultsPerPage` and if not is given set it to the value given for maxResult

This will make it possible to get rid of the logic in `utils -> getResourceOptions` and only to the transformation from camelCase to snake_case there.

2022-09-16 13:25 UTC, raae commented on gatsby-node.js
> +    resourceType: Joi.string().default('image'),
nitpick: remove double entry

2022-09-18 05:51 UTC, raae requested changes

2022-09-18 05:51 UTC, raae commented on gatsby-node.js
> +    resultsPerPage: Joi.string().default('image'),
suggestion(blocking): It should be a number like max results and default should be set to the value of max result. See my comment above on how to achieve that.

2022-09-18 05:53 UTC, raae requested changes

2022-09-18 05:53 UTC, raae commented on gatsby-node.js
> +    resultsPerPage: Joi.string().default('image'),
Oh I see now that you switched up `resourceType` and `resultsPerPage`.

2022-09-27 07:38 UTC, olavea commented
How do we test it?

2022-09-27 08:12 UTC, raae reviewed
praise: looks good, I'll give it go and add jest tests before approving

2022-09-27 08:19 UTC, raae commented
> How do we test it?

The best is automated Jest tests, I'll add it to this repo after rebasing to main for you.

2022-09-27 11:53 UTC, raae commented
Closing this, you can open a PR towards cloudinary-dev

2022-09-27 11:53 UTC, closed without merging